server:
  port: 8080 # ???? ??

spring:
  profiles:
    active: dev # ????? application-dev.yml? ???

  datasource:
    hikari: # ?? ??? ??? ??
      auto-commit: false # ?? ?? ?? -> ? ?????? set autocommit=1? ???? ??

  jpa:
    properties: # -> ??? hibernate? sql ??? ? ? ??? ?? ???
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true


    hibernate:
      ddl-auto: update # create ?? update <- DB ??? or ?? ??
    show-sql: true # ??? sql ??? ???? ??

logging: # ??? ??? ?? ?? ??? ??? ??? ?? ?? ??? ????
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE